default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: complements_io_development

test:
  <<: *default
  database: compliments_io_test

production:
  <<: *default
  database: compliments_io_production
