default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: db
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *default
  database: compliments_io_development

test:
  <<: *default
  database: compliments_io_test

production:
  <<: *default
  database: compliments_io_production
